111 - スキーマを追加
OIC-Odin/smart-remote pull request #125
Opened 2017-02-08 05:30 UTC by youmjww

# 説明
button layoutのDBにアクセスするところにスキーマが無かったのでスキーマを追加しました

# issus
[#111 ButtonLayoutのスキーマ](#111)

2017-02-08 13:02 UTC, Dimda requested changes

2017-02-08 13:02 UTC, Dimda commented on imports/api/button_layout/button_layout.js
> +  "buttons.$": {
`buttons.$`は配列に入っているものを示している。この場合それはオブジェクト。そのオブジェクにはスキーマを作る必要はない、中に 入ってるもの( `buttons.$buttonId`, `buttons.$.registryId`) の為にスキーマを作って。:smiley:

2017-02-15 07:53 UTC, Dimda commented on imports/api/button_layout/button_layout.js
> +
改行は他のところにはないから、ない方がいいと思う。

2017-02-15 07:56 UTC, youmjww commented on imports/api/button_layout/button_layout.js
> +
対応しました

2017-02-15 08:02 UTC, Dimda requested changes

2017-02-15 08:02 UTC, Dimda commented on imports/api/button_layout/button_layout.js
> +  "buttons.$buttonId": {
`"buttons.$.buttonId"`になっているはず。

2017-02-15 08:07 UTC, youmjww commented on imports/api/button_layout/button_layout.js
> +  "buttons.$buttonId": {
対応しました

2017-02-15 08:09 UTC, Dimda approved these changes

2017-02-15 08:09 UTC, merged