Feature/8 add login and register page
OIC-Odin/smart-remote pull request #44
Opened 2016-11-29 07:10 UTC by Tyokopai

# 説明
registerページの作成
enroll-accountページの作成
フォームのバリデーションチェックの作成
ユーザースキーマの変更
package.jsonの追記
バリデーション用のi18nの作成
registerのi18nの記述を一部修正

# 備考
enroll-accountページのend to endテストがトークン取得ができない問題で完了していないので、手動でチェックしてほしい
### enroll-accountのバリデーションリスト
- password
  - required
  - 8-16文字の範囲でないとエラーが出る
- confirm password
  - required
  - passwordと同じ文字列でないとエラーが出る
- country
  - 国を選択しないとエラーがでる
- city
  - required

# issue
[ユーザーログイン・登録画面作成](https://github.com/OIC-Odin/smart-remote/issues/8)

2016-12-02 04:35 UTC, gucchii approved these changes

2016-12-02 05:32 UTC, gucchii approved these changes

2016-12-02 05:45 UTC, gucchii requested changes
タスクには書いてありませんでしたが、言語選択の情報をユーザー情報として登録する必要があるので修正の方よろしくお願いします。

2016-12-06 02:21 UTC, youmjww commented on imports/startup/client/routes.jsx
>  import { render } from 'react-dom';
ここでは使われていないと思います

2016-12-06 03:03 UTC, reiri requested changes

2016-12-06 03:03 UTC, reiri commented on imports/api/validator/form_validator.js
> +import React from 'react';
Generalチャットの投票で拡張子はつけることになったので拡張子をお願いします

2016-12-06 04:56 UTC, youmjww commented
・enroll-accountのページでページタイトルとselect countryと都市を選ぶところがi18nに対応していない
・言語選択でjaが選択されているときはselect countryで日本を上に持ってきている方がユーザーさんが使いやすいかも

2016-12-06 05:04 UTC, Tyokopai commented
現状使っている国、都市選択のコンポーネントが外部のもので、i18nを適用できない。
ダービスと話した結果、他にも優先するべき機能などがたくさんあるので、とりあえずこのまま実装し、余裕があれば随時対応していくという結論になった。
2番目の項目についても同上。

2016-12-06 05:22 UTC, Tyokopai commented on imports/api/validator/form_validator.js
> +import React from 'react';
既存のnpmパッケージやmeteorパッケージを使うとき、拡張子を付けたら動かなくなる。
統一感をもたせるなら拡張子は無しがいいと思う

2016-12-06 09:43 UTC, youmjww approved these changes

2016-12-08 00:38 UTC, Dimda commented
@reiri @gucchii これのレビュー状態は？自分が求めていた変更は修正された？

2016-12-09 00:34 UTC, reiri approved these changes

2016-12-09 01:01 UTC, gucchii approved these changes

2016-12-09 01:02 UTC, merged