66 - smart remoteのデバイスのまとめ
OIC-Odin/smart-remote pull request #71
Opened 2017-01-09 07:05 UTC by Hideyasu

# 説明
クラウドIDE上のスマートリモコンのコードをまとめた
デバック用のコードも削除した

# 解決策
まとめた

# issue
[パスワードのリセット機能](https://github.com/OIC-Odin/smart-remote/issues/66)

2017-01-10 02:49 UTC, reiri requested changes

2017-01-10 02:49 UTC, reiri commented on photon/smart_remote.ino
> +    for( int indexHighLow = 0; indexHighLow < countHighLow; indexHighLow++ )
空白

2017-01-10 02:49 UTC, reiri commented on photon/smart_remote.ino
>      if( state != state_prev )
空白

2017-01-12 02:33 UTC, Dimda requested changes

2017-01-12 02:33 UTC, Dimda commented on photon/smart_remote.ino
> +String jinkan = "";
日本語で変数を使うなら前のやつも全部日本語に変えるのがいい。そうじゃないなら`motionDetector`とか使ったら？どっちかに統一させて。

2017-01-12 02:33 UTC, Dimda commented on photon/smart_remote.ino
> +unsigned long jinkanTime;
また日本語の変数でてるから上のコメントと同じように対応をお願い。

2017-01-12 02:33 UTC, Dimda commented on photon/smart_remote.ino
> +  {
この中括弧をelseのところに移動

2017-01-12 02:33 UTC, Dimda commented on photon/smart_remote.ino
> +        {
この中括弧をelseのところに移動

2017-01-12 02:33 UTC, Dimda commented on photon/smart_remote.ino
> +        }
インデントがずれてる

2017-01-12 02:33 UTC, Dimda commented on photon/smart_remote.ino
>      {
この中括弧をelseのところに移動

2017-01-12 02:33 UTC, Dimda commented on photon/smart_remote.ino
>          {
この中括弧をelseのところに移動

2017-01-13 07:15 UTC, Hideyasu commented on photon/smart_remote.ino
> +String jinkan = "";
motionに統一しました

2017-01-13 07:16 UTC, Hideyasu commented on photon/smart_remote.ino
> +unsigned long jinkanTime;
motionTimeに変更しました

2017-01-13 07:16 UTC, Hideyasu commented on photon/smart_remote.ino
> +    for( int indexHighLow = 0; indexHighLow < countHighLow; indexHighLow++ )
対応しました

2017-01-13 07:16 UTC, Hideyasu commented on photon/smart_remote.ino
>      if( state != state_prev )
対応しました

2017-01-14 03:26 UTC, Dimda approved these changes

2017-01-15 16:52 UTC, Dimda requested changes

2017-01-15 16:52 UTC, Dimda commented on photon/test.ino
> +// This #include statement was automatically added by the Particle IDE.
このファイルって何？コミットこれについて何も書いてない。

2017-01-15 16:52 UTC, Dimda commented on photon/smart_remote.ino
> +	for  ( int indexHighLow = 0; indexHighLow < countHighLow; indexHighLow++ ) {
ここスペース二つ入ってない？

2017-01-17 02:31 UTC, Dimda approved these changes

2017-01-19 23:04 UTC, reiri approved these changes

2017-01-19 23:04 UTC, merged