17 - ボタンパネルの赤外線情報を登録するための機能
OIC-Odin/smart-remote pull request #72
Opened 2017-01-13 05:02 UTC by gucchii

# 説明
photon情報を登録するadd-photonページの作成
ボタンの赤外線情報を登録するbutton-registerページの作成

#Issues
[button-panelを登録できる](https://github.com/OIC-Odin/smart-remote/issues/17)

2017-01-14 06:59 UTC, reiri requested changes

2017-01-14 06:59 UTC, reiri commented on imports/startup/client/routes.jsx
>  import Register from '../../ui/layouts/Register.jsx';
.jsxの削除

2017-01-14 16:19 UTC, Dimda commented
@reiri 修正終わった。それ以外にも色んな問題点みつけて修正した。

2017-01-15 11:39 UTC, reiri approved these changes

2017-01-15 12:11 UTC, merged